

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      #    -   id: trailing-whitespace
      #    -   id: end-of-file-fixer
      #    -   id: check-yaml
    -   id: check-added-large-files

- repo: https://github.com/PyCQA/bandit
  rev: '1.7.4'
  hooks:
  - id: bandit
    #args: ["-r", "nbdev_mkdocs"]

- repo: https://github.com/returntocorp/semgrep
  rev: "v1.61.1"
  hooks:
    - id: semgrep
      name: Semgrep 
      args: ["--config", "auto", "--error"]

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
    - id: detect-secrets
      args: ["--baseline", ".secrets.baseline"]
