ARG BASE=ubuntu:latest

#FROM ubuntu:latest
FROM ${BASE}
ARG BASE

LABEL org.opencontainers.image.source https://github.com/airtai/nbdev-mkdocs

ENV DEBIAN_FRONTEND noninteractive

RUN apt update

RUN apt-get install --only-upgrade linux-libc-dev
RUN apt-mark hold cuda-compat-11-2 cuda-cudart-11-2 cuda-nvtx-11-2 libcusparse-11-2 libnpp-11-2 \
      libcudnn8 libnvinfer-plugin7 libnvinfer7


# install security updates
RUN apt update --fix-missing --yes
RUN apt update -y && apt install --assume-yes \
  apt-utils git zip curl sudo wget vim fish pip htop nano less wget openssh-client \
  software-properties-common \
  && apt purge --auto-remove && apt clean && rm -rf /var/lib/apt/lists/*

RUN python3 -V
RUN python3 -m pip install --upgrade pip

COPY top_level_requirements.txt .
RUN python3 -m pip install --no-cache-dir -r top_level_requirements.txt && rm top_level_requirements.txt

# Install node and npm
RUN curl -fsSL https://deb.nodesource.com/setup_19.x | bash - && apt-get install -y nodejs \
    && apt purge -y --auto-remove && apt clean && rm -rf /var/lib/apt/lists/*

RUN nbdev_install_quarto

# Install and configure jupyter notebook
## Install and enable black python formatter for notebooks
RUN jupyter nbextension install https://github.com/drillan/jupyter-black/archive/master.zip \
    && jupyter nbextension enable jupyter-black-master/jupyter-black

## Install jupyter theme with airt theme
RUN python3 -m pip install --no-cache-dir git+https://github.com/airtai/jupyter-themes.git

## Customize your jupyter notebook
COPY airt-neg-trans-small.png /tmp
RUN chmod 644 /tmp/airt-neg-trans-small.png
COPY airt_favicons /tmp/airt_favicons
RUN chmod -R 755 /tmp/airt_favicons
# RUN jt -t airtd -cellw 90% -N -T --logo /root/airt-neg-trans-small.png --fav_icon_dir /root/airt_favicons
# RUN rm -rf /root/airt-neg-trans-small.png /root/airt_favicons

## Set default shell and home for jupyter notebook
ENV SHELL /usr/bin/bash

#RUN mkdir /work && mkdir /work/.config && chmod 777 /work && chmod 777 /work/.config
RUN mkdir /work && chmod 777 /work
# ENV HOME /work
WORKDIR /work

COPY nvtop-20.04 /usr/local/bin/nvtop

# Configure entrypoint and serve jupyter notebook
ENTRYPOINT []
COPY user_startup.sh /var
RUN chmod 777 /var/user_startup.sh
CMD ["/bin/bash", "-c", "chown -R $USER /home/$USER && sudo -u $USER /var/user_startup.sh && sudo --preserve-env=\"$PRESERVE_ENVS\" -u $USER PATH=$PATH:/home/$USER/.local/bin jupyter notebook --ip 0.0.0.0 --no-browser --allow-root"]
EXPOSE 8888

COPY set_bob_the_fish.sh /bin
RUN chmod 755 /bin/set_bob_the_fish.sh

