name: Deploy nbdev-mkdocs generated documentation to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          cfg_file=.ghp-config
          if [[ -f "$cfg_file"  ]] && grep -q "USE_NBDEV_MKDOCS_PRE=true" "$cfg_file"
          then
            pip install 'nbdev[dev]'
            nbdev_install_quarto
            make
          else
            pip install -Uq nbdev
            nbdev_install_quarto
            pip install nbdev_mkdocs
            pip install -e ".[dev]"
            nbdev_mkdocs prepare
          fi
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./mkdocs/site
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
