# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/PackageData.ipynb.

# %% auto 0
__all__ = ['get_root_data_path']

# %% ../nbs/PackageData.ipynb 1
from typing import *

from pathlib import Path

# %% ../nbs/PackageData.ipynb 2
def get_root_data_path() -> Path:
    """Returns path to package_data in lib

    Example:
        ``` python
        from nbdev_mkdocs._package_data import get_root_data_path

        req_path = get_root_data_path() / "requirements.txt"
        print(f"Path is: {req_path.resolve()}")
        assert req_path.exists()

        ```

    """
    return Path(__file__).parent / "package_data"
