#name: Deploy to GitHub Pages
#on:
#  push:
#    branches: [ "main", "master" ]
#  workflow_dispatch:
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps: [uses: fastai/workflows/quarto-ghp@master]


name: Deploy nbdev-mkdocs generated documentation to GitHub Pages
on:
  push:
    branches:
      - master 
      - main
      - nbdev2
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install nbdev
      - run: make mkdocs/site
      - run: cd mkdocs; mkdocs gh-deploy --force

