name: Deploy nbdev-mkdocs generated documentation to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -Uq nbdev
          nbdev_install_quarto
          cfg_file=.ghp-config
          if [ -f "$cfg_file" ] && grep -q "USE_NBDEV_MKDOCS_PRE=true" "$cfg_file"
          then
            echo "Installing nbdev_mkdocs from local"
          else
            pip install nbdev-mkdocs
          fi
          test -f setup.py && pip install -e ".[dev]"
          nbdev_mkdocs docs
      - name: Enable GitHub Pages
        shell: python
        run: |
          import ghapi.core,nbdev.config,sys
          msg="Please ensure GitHub Pages can publish from the root of the `gh-pages` branch per these instructions - https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch"
          try:
            api = ghapi.core.GhApi(owner=nbdev.config.get_config().user, repo=nbdev.config.get_config().repo, token="${{ secrets.GITHUB_TOKEN }}")
            api.enable_pages(branch='gh-pages')
          except Exception as e:
            print(f'::warning title="Could not enable GitHub Pages Automatically":: {msg}\n{e}')
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./mkdocs/site
          # The following lines assign commit authorship to the official GH-Actions 
          # bot for deploys to `gh-pages` branch. You can swap them out with your own 
          # user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
