name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  static_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: make static_check
  test:
    strategy:
      fail-fast: true
      matrix:
        os:  [ubuntu, macos]
        version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}-latest

    steps: 
      - name: install quarto
        run: |
	wget -q $(curl https://latest.fast.ai/latest/quarto-dev/quarto-cli/linux-amd64.deb)
	sudo dpkg -i quarto*.deb
      - uses: fastai/workflows/nbdev-ci@master
        with:
          version: ${{ matrix.version }}

