name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  check_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install 'nbdev[dev]'
      - name: Install Quarto
        shell: bash
        run: |
          wget -q $(curl https://github.com/quarto-dev/quarto-cli/releases/download/v1.1.251/quarto-1.1.251-linux-amd64.deb)
          sudo dpkg -i quarto*.deb
          quarto --help
      - run: make check_all

