name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  static_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -U nbdev black
      - run: make static_check
  test:
    strategy:
      fail-fast: true
      matrix:
        os:  [ubuntu]
        version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}-latest

    steps: 
      - name: Install quarto
        run: |
          if [ ${{ matrix.os == 'ubuntu' }} ]; then
            wget -q $(curl https://latest.fast.ai/pre/quarto-dev/quarto-cli/linux-amd64.deb)
            sudo dpkg -i quarto*.deb
          else
            wget -q $(curl https://www.quarto.org/download/latest/quarto-macos.pkg)
            sudo installer -pkg quarto-macos.pkg -target /
          fi
      - uses: fastai/workflows/nbdev-ci@master
        with:
          version: ${{ matrix.version }}

